Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "testmatch"
executable              = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TprimeToTZ_1800_2022/file3/runner.sh
arguments               = $(Proxy_path)
output                  = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TprimeToTZ_1800_2022/condor/output/TprimeToTZ_1800_2022_file3.out
error                   = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TprimeToTZ_1800_2022/condor/error/TprimeToTZ_1800_2022_file3.err
log                     = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TprimeToTZ_1800_2022/condor/log/TprimeToTZ_1800_2022_file3.log
queue
