Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "testmatch"
executable              = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TT_hadr_2022/file0/runner.sh
arguments               = $(Proxy_path)
output                  = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TT_hadr_2022/condor/output/TT_hadr_2022_file0.out
error                   = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TT_hadr_2022/condor/error/TT_hadr_2022_file0.err
log                     = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/condor/tmp//TT_hadr_2022/condor/log/TT_hadr_2022_file0.log
queue
