Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "testmatch"
+JobTag                 = "DataJetMETD_2022"
executable              = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection_xTopSF/condor_preprocess/DataJetMETD_2022/runner.sh
arguments               = $(Proxy_path)
output                  = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection_xTopSF/condor_preprocess/DataJetMETD_2022/condor/output/preprocess_DataJetMETD_2022.out
error                   = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection_xTopSF/condor_preprocess/DataJetMETD_2022/condor/error/preprocess_DataJetMETD_2022.err
log                     = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection_xTopSF/condor_preprocess/DataJetMETD_2022/condor/log/preprocess_DataJetMETD_2022.log
queue
