Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/l/lfavilla/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "nextweek"
+JobTag                 = "TT_hadr_2023postBPix_syst_no_puWeight"
executable              = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection/condor/TT_hadr_2023postBPix_syst_no_puWeight/runner.sh
arguments               = 
output                  = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection/condor/TT_hadr_2023postBPix_syst_no_puWeight/condor/output/postSelector_TT_hadr_2023postBPix.out
error                   = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection/condor/TT_hadr_2023postBPix_syst_no_puWeight/condor/error/postSelector_TT_hadr_2023postBPix.err
log                     = /afs/cern.ch/user/l/lfavilla/TprimeAnalysis/NanoAODTools/python/postprocessing/postselection/condor/TT_hadr_2023postBPix_syst_no_puWeight/condor/log/postSelector_TT_hadr_2023postBPix.log
queue
